### ISSUE TITLE
NullPointerException onHideAnimationCompleted

### ISSUE THREAD

**Issue by cagkanciloglu** [shehabic/Droppy#56]
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
       at com.shehabic.droppy.DroppyMenuPopup.dismissPopup(DroppyMenuPopup.java:152)
       at com.shehabic.droppy.DroppyMenuPopup.hideAnimationCompleted(DroppyMenuPopup.java:138)
       at com.shehabic.droppy.animations.DroppyFadeInAnimation$1.onAnimationEnd(DroppyFadeInAnimation.java:30)
       at android.view.animation.Animation.fireAnimationEnd(Animation.java:932)
       at android.view.animation.Animation.getTransformation(Animation.java:886)
       at android.view.animation.Animation.getTransformation(Animation.java:952)
       at android.view.View.applyLegacyAnimation(View.java:16671)
       at android.view.View.draw(View.java:16787)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3768)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3578)
       at android.view.View.updateDisplayListIfDirty(View.java:16060)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
       at android.view.View.updateDisplayListIfDirty(View.java:16028)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
       at android.view.View.updateDisplayListIfDirty(View.java:16028)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
       at android.view.View.updateDisplayListIfDirty(View.java:16028)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:657)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:663)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:771)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2808)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2616)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2223)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Comment by JosefHruska** [comment]
We have the same problem. I am going to create a PR which will fix it. It should be ready in a few days.

**Comment by davidvavra** [comment]
Hi, we have released our for which fixes this to the jcenter: `compile 'io.stepuplabs.droppy:droppy:0.6.1.0'`

**Comment by afgaiel** [comment]
Shall I remove this line 

> `implementation 'com.shehabic.droppy:Droppy:0.6.0@aar'` or should be kept with `compile 'io.stepuplabs.droppy:droppy:0.6.1.0'`

**Comment by davidvavra** [comment]
Replace droppy dependency with our dependency
