### ISSUE TITLE
Got a crash on lower devices. 

### ISSUE THREAD

**Issue by ShivamDev31** [shehabic/Droppy#57]
Got a crash while opening the popup on API level 19.

`FATAL EXCEPTION: main
                                                                            Process: com.test.office, PID: 3710
                                                                            android.content.res.Resources$NotFoundException: File res/drawable/ic_vector_agenda_view.xml from drawable resource ID #0x7f020138. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
                                                                                at android.content.res.Resources.loadDrawable(Resources.java:3451)
                                                                                at android.content.res.Resources.getDrawable(Resources.java:1894)
                                                                                at com.android.internal.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:388)
                                                                                at com.shehabic.droppy.DroppyMenuPopup$Builder.fromMenu(DroppyMenuPopup.java:381)
                                                                                at  com.test.office.features.home.appointment.AppointmentListFragment.toggleView(AppointmentListFragment.java:177)
                                                                                at  com.test.office.features.home.appointment.AppointmentListFragment_ViewBinding$1.doClick(AppointmentListFragment_ViewBinding.java:34)
                                                                                at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                at android.view.View.performClick(View.java:4508)
                                                                                at android.view.View$PerformClick.run(View.java:18675)
                                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5584)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                             Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
                                                                                at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:969)
                                                                                at android.graphics.drawable.Drawable.createFromXml(Drawable.java:913)
                                                                                at android.content.res.Resources.loadDrawable(Resources.java:3447)
                                                                                at android.content.res.Resources.getDrawable(Resources.java:1894) 
                                                                                at com.android.internal.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:388) 
                                                                                at com.shehabic.droppy.DroppyMenuPopup$Builder.fromMenu(DroppyMenuPopup.java:381) 
                                                                                at  com.test.office.features.home.appointment.AppointmentListFragment.toggleView(AppointmentListFragment.java:177) 
                                                                                at  com.test.office.features.home.appointment.AppointmentListFragment_ViewBinding$1.doClick(AppointmentListFragment_ViewBinding.java:34) 
                                                                                at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
                                                                                at android.view.View.performClick(View.java:4508) 
                                                                                at android.view.View$PerformClick.run(View.java:18675) 
                                                                                at android.os.Handler.handleCallback(Handler.java:733) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5584) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                                at dalvik.system.NativeStart.main(Native Method) `

**Comment by oseamiya** [comment]
Crash on API 27 , Oppo A51 too
